local: &local
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
development: *local
test: *local
production: &production
  :url: redis://redistogo:601c371a8832eda570fe044e5badbcb9@soapfish.redistogo.com:10157
  :host: soapfish.redistogo.com
  :port: 10272
  :password: 601c371a8832eda570fe044e5badbcb9
  :inline: true
  :timeout: 1
